<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>catch</title>
</head>
<body>
<script>
    function processData(data) {
        return new Promise(function (resolve, reject) {
            let randomValue = Math.floor(Math.random() * 5001)

            setTimeout(() => {
                if (randomValue > 1000) {
                    console.log(`Дані ${data} оброблені за ${randomValue}.`)
                    resolve(data + randomValue)
                } else {
                    reject(new Error("Помилка під час обробки даних" + data))
                }
            }, randomValue)
        })
    }

    let initialData = 10

    processData(initialData)
        .then(data => processData(data))
        .then(data => processData(data))
        .then(data => processData(data))
        .then(data => processData(data))
        .catch(error => console.error(error.message)) // якщо один із промісів завершується з помилкою то управління переходить
    // До найближчого catch
</script>
</body>
</html>
